### ISSUE TITLE
Feature Request - Adding support for a download button

### ISSUE THREAD

**Issue by ghost** [gkaemmer/react-pdf-pages#4]
It'd be nice if react-pdf-pages added support for downloading a PDF that is currently loaded in view. I _believe_ PDF.js has this option, though I'm not 100% sure. 

This would allow PDF's that require custom headers to be downloaded (and I'd think it might also speed up the download in general).

**Comment by ghost** [comment]
I *think* something like this might work: 

`
window.PDFJS.getDocument(initObject).then(function getRawDataFromPDF(pdf) {
  pdf.getData().then(function(arrayBuffer) {
    const pdfraw = String.fromCharCode.apply(null, arrayBuffer);
    this.props.onRawPDFGiven(pdfraw);
  }
});
`

I'll try it on my forked repo.

**Comment by gkaemmer** [comment]
Interesting--it's probably worth just adding some way of accessing the raw PDF file object to give an escape hatch for things like this. Maybe just passing a second optional `file` argument to `onComplete()`.

Think that would be enough for this use case?

**Comment by ghost** [comment]
Yeah, that'd be great.

**Comment by gkaemmer** [comment]
Released in v0.1.7
