### ISSUE TITLE
HTML version & React-Virtualized

### ISSUE THREAD

**Issue by oyeanuj** [gkaemmer/react-pdf-pages#5]
Hi @gkaemmer, thank you for putting out this library. I noticed your little note about using `react-virtualized` in the README. Do you have an example for the same?

I was also curious if you were considering a HTML render (rather than Canvas) like in the main example for `pdf.js` -  https://mozilla.github.io/pdf.js/web/viewer.html

Thanks!

**Comment by gkaemmer** [comment]
Hey @oyeanuj, thanks for dropping in! I have actually put some time into making a `react-virtualized` wrapper around `react-pdf-pages` but it requires some other dependencies and has some ugly bits so I haven't published it.

The gist is this: 
```
import AutoSizer from "react-virtualized/dist/commonjs/AutoSizer";
import List from "react-virtualized/dist/commonjs/List";
...
<AutoSizer>
  {(width, height) => (
    <List
      noRowsRenderer={() => <div>Nothing</div>}
      rowCount={this.pages.length}
      overscanRowCount={2}
      rowHeight={
        this.state.pageHeight // You have to keep track of pageHeight yourself!
      }
      rowRenderer={({ index, isScrolling, key, style }) => {
        <div key={key} style={style}>
          <Page
            page={this.pages[index]}
            onSizeReady={
              this.state.pageHeight // Don't pass handler if pageHeight is already defined
                ? undefined
                : (width, height) => this.setState({ pageHeight: height })
            }
          />
        </div>
      }}
      width={width}
      height={height}
    />
  )}
</AutoSizer>
```

The key challenge is keeping track of `pageHeight`, which **you must assume is the same** for every page of your document (otherwise react-virtualized will crop pages). If you want to add padding between pages, or add other custom styles around each `Page`, you can edit the `rowRenderer` prop on `List`.

**Comment by gkaemmer** [comment]
As far as HTML rendering--I think what you're referring to is the PDF "text layer", which you can find some more details about here: https://github.com/mozilla/pdf.js/issues/7072. The idea is not to avoid using canvas--there still is a canvas element underneath. The text layer gets rendered on top as a bunch of absolutely positioned divs with hidden text.

As far as implementing with `react-pdf-pages`: with the raw `file` object (passed as the second argument to `onComplete`), I think you could hack together the rendering of the text layer, using a `position: relative` div around each `Page`. I haven't ever actually built the text layer myself--most PDFs I deal with are scanned images.

If you can figure out a clean way of doing this, definitely let me know! I'd love to make this a drop-in feature for the library.

**Comment by oyeanuj** [comment]
@gkaemmer Thanks for all of that information. I'll study this a little bit more. Its clearly more complicated than I thought (atleast for my usecase), but I'll report back if I have any updates or findings!

**Comment by gkaemmer** [comment]
Awesome, looking forward to hearing what you find!
